<Project Sdk="Aspire.AppHost.Sdk/13.3.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0e5be444-0eb2-409f-9f1c-fb2e11860efa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoviePicks.Api\MoviePicks.Api.csproj" />

    <!--
      The IsAspireProjectResource="false" attribute tells Aspire to treat this
      reference as a standard project reference.

      References:
        - Custom hosting integrations: https://aspire.dev/integrations/custom-integrations/hosting-integrations/
        - Compiler Warning ASPIRE004:  https://aspire.dev/diagnostics/aspire004/
    -->
    <ProjectReference Include="..\MoviePicks.Contracts\MoviePicks.Contracts.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\MoviePicks.Web\MoviePicks.Web.csproj" />
  </ItemGroup>

</Project>
